algorithm: fixmatch
save_dir: ./saved_models/openset_cv
save_name: fixmatch_das6_p5
resume: True
load_path: ./saved_models/openset_cv/fixmatch_das6_p5/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 100
num_train_iter: 50000
num_eval_iter: 500
num_labels: 260
labeled_percent: p5
batch_size: 32
eval_batch_size: 128
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 2
ema_m: 0.999
crop_ratio: 0.875
img_size: 224
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: True
clip: 0.0
use_cat: True
net: resnet18
net_from_name: False
data_dir: ./data
dataset: das6
train_sampler: RandomSampler
num_classes: 3
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
