algorithm: openmatch
save_dir: ./saved_models/openset_cv
save_name: openmatch_das6_15_pretrain
resume: True
load_path: ./saved_models/openset_cv/openmatch_das6_15_pretrain/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 100
num_train_iter: 51200
num_eval_iter: 512
num_labels: 1250
labeled_percent: 15
batch_size: 32
eval_batch_size: 128
p_cutoff: 0
ulb_loss_ratio: 1.0
lambda_em: 0.1
lambda_socr: 0.5
start_fix: 5
uratio: 2
fix_uratio: 2
ema_m: 0.999
crop_ratio: 0.875
img_size: 224
optim: SGD
lr: 0.01
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet18
net_from_name: False
data_dir: ./data
dataset: das6
train_sampler: RandomSampler
num_classes: 3
num_workers: 4
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
use_pretrain: True
