algorithm: scomatch
resume: True
overwrite: True
use_tensorboard: True
epoch: 100
num_train_iter: 20000
num_eval_iter: 200
num_labels: 260
labeled_percent: 75
batch_size: 64
eval_batch_size: 128
T: 0.5
p_cutoff: 0.95
q_cutoff: 0.5
ulb_loss_ratio: 1.0
uratio: 2
da_len: 32
ema_m: 0.999
crop_ratio: 0.875
img_size: 224
optim: SGD
lr: 0.01
momentum: 0.9
weight_decay: 0.0003
layer_decay: 1.0
amp: True
clip: 0.0
use_cat: True
net_from_name: False
data_dir: ./data
dataset: das6
train_sampler: RandomSampler
num_classes: 3
num_workers: 4
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10055
dist_backend: nccl
gpu: None
use_rot: True